### ISSUE TITLE
[Collection/NFT] Momento collections

### ISSUE THREAD

**Issue by Marec4** [NFT-Limited/nf-bugs#109]
**Describe the issue**
We (or even Bithomp) can't show the media from any of the Momento (https://momentofans.com/) collections. 

**Details**
Help us to identify the collection by providing some infos:

REQUIRED

Few example collections:

1. Issuer address: rfCB45NCbdz5nd9hcpfjUBrb68iFUKJ943
2. Collection Taxon: 0

1. Issuer address: rrsC74D9NKbBGUQjcCjdHzutJdejCwrDqu
2. Collection Taxon: 0

1. Issuer address: rQnmgJf1kiLrVwkbN8Tazeu3oM7XEEamFr
2. Collection Taxon: 0

**Comment by viktorhugo** [comment]
reference to videos cannot be played
