### ISSUE TITLE
[BUG] Stop rendering home screen on deeplinked NFTs

### ISSUE THREAD

**Issue by danielwwf** [NFT-Limited/nf-bugs#114]
**Describe the bug**
The home screen gets rendered first if you open a deep link for an NFT. We should skip that as it will save 2 to 3 seconds on showing the actual NFT.

**Comment by Marec4** [comment]
It's still the same


https://github.com/NFT-Limited/nf-bugs/assets/25827470/0f464bd5-2adc-477c-9a4f-894a01d080d5

**Comment by viktorhugo** [comment]
I don't think this behavior can be changed, since the application must be started to be able to consult the nft and display it

**Comment by Marec4** [comment]
ok, then let's leave it as it is.
