### ISSUE TITLE
[Collection/NFT] MONKEE ADVENTURE SOUNDTRACKS

### ISSUE THREAD

**Issue by Marec4** [NFT-Limited/nf-bugs#123]
**Describe the issue**
Not showing any images from the collection. Reset not working.

All the NFT's include external link to Sonarmuse. The link should be shown.

**Details**
Help us to identify the collection by providing some infos:

REQUIRED
1. Issuer address: rfsuQDie8MqtkkTUdHmyR2oJa4Dp7bt1iF
2. Collection Taxon: 0

**Comment by Marec4** [comment]
Nothing is shown in the app

![Image](https://github.com/NFT-Limited/nf-bugs/assets/25827470/39d4dca8-fc20-4c78-9585-a6c3c9c493ad)

**Comment by Marec4** [comment]
Still the same

**Comment by viktorhugo** [comment]
![Image](https://github.com/NFT-Limited/nf-bugs/assets/14018194/b0b6759c-a339-4139-ba83-fcaac0372915)

on prodtest

**Comment by Marec4** [comment]
Yeah I'm seeing it now.

The collection is all about soundtracks and each one of them has an external URL to a specific song. Can we add a separate dropdown to the NFT detail view called: "External URL".

https://bithomp.com/nft/00083A98425D5408873C7C141C270879D254C84AC1CC10F0CF746543000033A8
