### ISSUE TITLE
[FEATURE REQUEST] Report an NFT

### ISSUE THREAD

**Issue by danielwwf** [NFT-Limited/nf-bugs#14]
**Is your feature request related to a problem? Please describe.**
There is no way to report an NFT inside the app.

**Describe the solution you'd like**
Add an option that allows users to flag an NFT. Ask users why the flag: General Issue OR Abusive/Illegal content.

**Describe alternatives you've considered**
None

**Additional context**
![image](https://user-images.githubusercontent.com/30388756/219950607-5b2928e5-63c2-4aae-bc67-79902d65a2ff.png)

**Comment by whywefight** [comment]
We need a report for this on the backend.
