### ISSUE TITLE
[BUG] Number of decimals

### ISSUE THREAD

**Issue by Marec4** [NFT-Limited/nf-bugs#168]
Please limit the number of decimals to the correct number. Currently, I can enter as much as I want to and it crashes the xApp.

![photo_2023-10-02_15-38-50](https://github.com/NFT-Limited/nf-bugs/assets/25827470/3a73be1d-e13b-476b-97ca-5de971f4c49d)

**Comment by Marec4** [comment]
The issue is back. I can enter as much decimals as I want and the app crashes after confirming. Please ensure all the fields have the checks.

**Comment by viktorhugo** [comment]
I'm sorry, I can't reproduce the error. Could you give me more details please? Currently, offers smaller than 0.000001 cannot be made.
I don't know what I'm missing


![Image](https://github.com/NFT-Limited/nf-bugs/assets/14018194/2b81fbce-3dfd-492a-bf7a-cc6a90cb49fd)

**Comment by Marec4** [comment]
Thats weird. I'm getting stuck on this: 
(xApp 0.4.9-prodtest) both iOS and Android


https://github.com/NFT-Limited/nf-bugs/assets/25827470/112a3095-a5ca-46b3-838b-38caefde74fb



https://github.com/NFT-Limited/nf-bugs/assets/25827470/0624deb5-d62b-446d-9e6f-b387b0ff4ef9
