### ISSUE TITLE
[BUG] Data updates in the xApp

### ISSUE THREAD

**Issue by Marec4** [NFT-Limited/nf-bugs#169]
After making/confirming a transaction the data is not refreshed in the app automatically after the transaction has been completed. Need to restart the xApp to see the changes.

**Comment by viktorhugo** [comment]
Could you please give more details of the error, a video would be great, please

**Comment by Marec4** [comment]
The NFT Digifish #297 was bought from another device. You can see the successful sell messages by the xApp but it does not update it on the grid view and when opening it still shows like you own it. Restarting the app fixes the data and the NFT is gone from the list.



https://github.com/NFT-Limited/nf-bugs/assets/25827470/434e6ce1-b0f7-4f3b-9f6a-9bdc2dc09007
