### ISSUE TITLE
[BUG] Accepting offer with active sell offer

### ISSUE THREAD

**Issue by Marec4** [NFT-Limited/nf-bugs#182]
NFT had an active sell offer for 10XRP. I received an offer for 1XRP and accepted the low offer. Now seems that I have 2 active sell offers and the NFT still hasn't changed the owner.

The sell should happen when I accept the offer.

https://bithomp.com/nft/000803E8CEC1EB1B331D8A55E39D451DE8E13F59CF5509D55AFF42C1000001B8

![photo_2023-10-12_14-48-56](https://github.com/NFT-Limited/nf-bugs/assets/25827470/5a034974-aac9-4f9c-a3b4-14c1763936b4)

**Comment by Marec4** [comment]
Ok, great, the transaction happened. 

As the sell offer remains invalid, can we show that information on the Account page under Sell Offers? Something like this:



![Image](https://github.com/NFT-Limited/nf-bugs/assets/25827470/811da238-3228-42fd-b5fa-63dcec1fd4f5)



Invalid offer notification on Bithomp:

![Image](https://github.com/NFT-Limited/nf-bugs/assets/25827470/760e404f-dc80-46aa-b3df-64b86f7d5b00)

**Comment by viktorhugo** [comment]
A method was added in which the user's offers and their corresponding nft are verified so that this does not happen

**Comment by Marec4** [comment]
The invalid Sell offer still stays as it's not Canceled by the owner. Check sell offers and then select "invalid". https://bithomp.com/nft/00082710A7A80B51B0BFF0228C298900C999E5659EEEFF5CE31FE7C00000004D

I think it's not possible to cancel this automatically so we should either show this information under the Sell offers or move the invalid offers to another tab on the account page.



![Image](https://github.com/NFT-Limited/nf-bugs/assets/25827470/90c94708-97fd-4614-95d5-ed159adffd2f)
