### ISSUE TITLE
[BUG] Backend not showing NFTs under collections

### ISSUE THREAD

**Issue by Marec4** [NFT-Limited/nf-bugs#184]
The backend is not showing NFTs under new collections.

![Screenshot 2023-10-25 095542](https://github.com/NFT-Limited/nf-bugs/assets/25827470/b20a1368-22fe-4ed1-9f04-1a7702b9fc46)

The NFTs do show up in the app.

![photo_2023-10-25_09-57-49](https://github.com/NFT-Limited/nf-bugs/assets/25827470/e45d7fa7-58a3-44c4-a28d-5889df8c2189)

**Comment by ajochems** [comment]
Issuer: rLsNPnuYJkJWcVi3RxFDUzNuh3QhZdPAk4
Taxon: 50907
