### ISSUE TITLE
[BUG] Most NFTs with price not showing up

### ISSUE THREAD

**Issue by Marec4** [NFT-Limited/nf-bugs#185]
Most NFTs with price set doesn't show up. For example this collection:

rHNAio638gpMrCtxMysxMe1GuNydB4fR8L
Taxon 5000

The xApp shows 6 NFTs with a price. In reality, there are around 60 NFTs with price.

https://github.com/NFT-Limited/nf-bugs/assets/25827470/049418a8-49d0-460c-b61c-6e19eb64a11d

https://xrp.cafe/collection/xmals-skulls
![Screenshot 2023-10-25 153830](https://github.com/NFT-Limited/nf-bugs/assets/25827470/457ad9f8-2e47-44df-9048-0464d8f8ee21)

**Comment by Marec4** [comment]
Seems like it's ok with the example collection. Opened another random collection: https://xrp.cafe/collection/xshrooms

Can't see the ones we are showing with price on the xrp cafe. So seems there are some data issues.


Our app
![Image](https://github.com/NFT-Limited/nf-bugs/assets/25827470/72303e64-2d7d-4703-88c6-0b8d30176eca)


xrp.cafe
![Image](https://github.com/NFT-Limited/nf-bugs/assets/25827470/6d2eea7a-3f49-415a-beb1-887f91517e0d)

**Comment by Marec4** [comment]
Still doesn't match:



![Image](https://github.com/NFT-Limited/nf-bugs/assets/25827470/d125a0e6-6f6a-411a-804b-5ec3f279044a)
![Image](https://github.com/NFT-Limited/nf-bugs/assets/25827470/ac18e443-a32d-4202-9c95-95c5bac05f55)

**Comment by viktorhugo** [comment]
There were offers that had been canceled but were already processed, let me know if you see any, the xapp also brings together all the available offers (onXRP, xrpCafe, those from us and those made outside)
For example: onxrp: https://nft.onxrp.com/collection/xshrooms/?sortBy=fixed_price&sortOrder=asc&collection=41227
xrpcafe: https://xrp.cafe/collection/xshrooms

**Comment by Marec4** [comment]
Yeah, I know about the different brokers. Thats why I added a screenshot from xrp.cafe as there were only their offers on the xApp screenshot.

I can see it's a bit better now. Will double-check in the morning and also with the collections. Thanks

**Comment by Marec4** [comment]
Checked several collections and it seemed ok. 

But still one issue with the xShrooms collection those. Srted with Price High and there are few xrp.cafe ones missing. Checked the backend and it seems this is data sync issue as we don't have the latest Sell Offers on those 2 NFTs that are missing from the list.

https://bithomp.com/nft/00081388C182B4F213B82CCFA4C6F59AD76F0AFCFBDF04D5CE6542670000078C
https://bithomp.com/nft/00081388C182B4F213B82CCFA4C6F59AD76F0AFCFBDF04D5C8B3DD9900001B3E


xApp


![Image](https://github.com/NFT-Limited/nf-bugs/assets/25827470/c8ac5c52-1182-4c9b-b010-6872e1d3f141)


xrp.cafe 


![Image](https://github.com/NFT-Limited/nf-bugs/assets/25827470/a0a373a1-1142-4e19-9946-b690ffc4579a)
