### ISSUE TITLE
[Bug] NFT info not showing

### ISSUE THREAD

**Issue by WietseWind** [NFT-Limited/nf-bugs#19]
Portfolio - open one of your tokens: none of the info shows (also: the picture not)

Applies to all NFTs in my account: `rwietsevLFg8XSmG3bEZzFein1g8RBqWDZ`

Overview (portfolio):
![image](https://user-images.githubusercontent.com/4756161/219958957-c3f39310-5c24-4600-b96b-2bf70153b8a9.png)

Tap one & details:
![image](https://user-images.githubusercontent.com/4756161/219958968-41ab47cc-e310-463c-acda-1e9155e4ec76.png)

**Comment by whywefight** [comment]
This seems to be an iOS issue, as its fine on Android. Restarting the app doesn't help.

**Comment by Marec4** [comment]
This is similar (if not the same) issue #8
