### ISSUE TITLE
[BUG] Bithomp as a Broker

### ISSUE THREAD

**Issue by Marec4** [NFT-Limited/nf-bugs#196]
Seems like bithomp is brokering NFTs by adding "bithomp.com" to the Memo. If clicking the link, will forward to bithomp but it's not shown on the image.

Can we accept the offer from the xApp? If not, show name bithomp as the broker.

https://bithomp.com/nft/000822B03EA060FD1026C04B2D390CC132D07D600DA9B08211D63555000022B9

![photo_2024-02-13_16-07-40](https://github.com/NFT-Limited/nf-bugs/assets/25827470/2cbf1dfa-7932-4cfd-af0a-4aad6f93161b)

**Comment by Marec4** [comment]
1. Buying Bithomp brokered NFTs seems to be working only with new offers. The old ones still do not show the broker name or the buy option.

2. Also, after buying a Bithomp brokered NFT, xapp shows a message "NFT successfully sold!". It should be the other way around.

**Comment by Marec4** [comment]
1. Seems to be the same, only showing Bithomp as a broker on new offers. Here's one with old one:


https://github.com/NFT-Limited/nf-bugs/assets/25827470/9f757e45-fccc-4072-9871-3f62760e82d9


2. It didn't show a message at all now. The "Hooray..." message should be shown with every purchase.

**Comment by viktorhugo** [comment]
Currently, when a buy offer is accepted from the xapp that has been created from bithomp, the message "Hooray, you have a new NFT!" and the account that created the offer receives the message "Bithomp brokered NFT successfully", in the same way if a Sell offer is created from bithomp and the purchase is made from the xapp, "Hooray, you have a new NFT!" and the account that created the offer receives the message "Bithomp brokered NFT successfully", in both cases I have tested and it receives the messages, if necessary, they are not shown, I could show it in a video or if any modification is needed

**Comment by Marec4** [comment]
For some reason, I'm not getting the notification. Here's a video of the process:



https://github.com/NFT-Limited/nf-bugs/assets/25827470/80b5ee0d-b838-4673-a88c-f184c3a6a13b

**Comment by Marec4** [comment]
Getting the notification now.

Now there's only the old offers issue left:

1. Buying Bithomp brokered NFTs seems to be working only with new offers. The old ones still do not show the broker name or the buy option.

**Comment by Marec4** [comment]
Still the same:



https://github.com/NFT-Limited/nf-bugs/assets/25827470/dd368676-f651-4fa2-ae7b-46cbd939bfec

**Comment by Marec4** [comment]
Still having issues. Here are 3 examples that do not show the bithomp as a broker:

1. https://bithomp.com/nft/00081388C182B4F213B82CCFA4C6F59AD76F0AFCFBDF04D5D2D643DF00000F04


![Image](https://github.com/NFT-Limited/nf-bugs/assets/25827470/d52c47bd-1470-476f-bbfc-487bdaf3f19a)



2. https://bithomp.com/nft/000827106CD2CBB743BE141A0FE7EA1F3177161ED3CCDCB2C36201B000000216


![Image](https://github.com/NFT-Limited/nf-bugs/assets/25827470/4cc68b2d-1b5a-4d17-a966-4e12d3f45537)



3. https://bithomp.com/nft/00081068C182B4F213B82CCFA4C6F59AD76F0AFCFBDF04D599C20BC0047F73E7



![Image](https://github.com/NFT-Limited/nf-bugs/assets/25827470/d6e71e39-6902-4b1e-9e7b-57036c3f568f)
