### ISSUE TITLE
[FEATURE REQUEST] Gridview Banners

### ISSUE THREAD

**Issue by Marec4** [NFT-Limited/nf-bugs#209]
After every 6 items in the gridview, add a banner space. We should be able to use as many different banners as we like by adding new ones with links in the backoffice.

If there's only 1 banner defined by us in the backend then show the same everywhere, if 2 defined, use it in the order: after 6 items, banner 1; after 12, banner 2; after 18, banner 1; after 24, banner 2, etc. The same repetition with more banners.

![Asset 12](https://github.com/NFT-Limited/nf-bugs/assets/25827470/593fbfd0-c554-4f8a-bb36-45ed774d43d1)
![Asset 22](https://github.com/NFT-Limited/nf-bugs/assets/25827470/5ebabee1-d51c-4c15-bf8c-79b4a356170f)

**Comment by Marec4** [comment]
Can't find the option to add gridview banners on the backend.

**Comment by viktorhugo** [comment]
In the backoffice there is a promotions section, add a promotion the recommended size is (360 x 144)

**Comment by Marec4** [comment]
Where can I select is it gridview banner or the main advertising area banner on the Home tab? We need to keep these separate.



![Image](https://github.com/NFT-Limited/nf-bugs/assets/25827470/bd556a28-2615-47c6-baa8-bf6fa6c177a6)

**Comment by Marec4** [comment]
Turned the 2 gridview banners in their back as advertising banners (The Ti Project and Combat Kanga). They do not appear again in the advertising area! I should be able to use any banner as an advertising banner and as a grid banner.

Also, please create separate areas for different types of banners. Something like this:


![Image](https://github.com/NFT-Limited/nf-bugs/assets/25827470/750d56c5-5ea9-40d6-af86-d13754b86c18)

**Comment by viktorhugo** [comment]
The functionality of updating the promotions to the xapp was added to the backoffice so that those that are being shown are updated, in addition, in the promotions view a flag is now also shown if it is dvertising banners or gridview banners in a single table

**Comment by Marec4** [comment]
Thanks.

If there are no promotions available, the placeholder shouldn't be there.

![Image](https://github.com/NFT-Limited/nf-bugs/assets/25827470/5e908a89-190f-4aeb-8e83-bb479160c396)

**Comment by Marec4** [comment]
Add gridview banners to all the views except "My NFTs" and "Favourites".
