### ISSUE TITLE
[BUG] Video goes fullscreen on iOS

### ISSUE THREAD

**Issue by Marec4** [NFT-Limited/nf-bugs#21]
**Describe the bug**
After pressing Play, the video goes immediately into fullscreen.

**To Reproduce**
Find an NFT with video.

**Expected behavior**
The video should play in the window and if I hit the fullscreen icon, then go into fullscreen.

**Screenshots**
https://user-images.githubusercontent.com/25827470/215755861-085c50a7-562b-4e8c-9da5-00db47a02884.mp4

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: 16.2
 - Non Fungible Version: 0.3.9
 - Non Fungible Theme: light mode
 - XUMM Version: 2.3.1.2
 - XUMM Theme: Default

**Comment by viktorhugo** [comment]
This only happens on iOS phones, I was investigating and in order to solve this you would have to edit a manifest.xml file from the xumm app and not in the xapp, so at the moment this problem cannot be solved, here is the code that would have to be edited
<platform name="ios">
     <preference name="AllowInlineMediaPlayback" value="true">
</platform>
