### ISSUE TITLE
[BUG] Grammar fixes

### ISSUE THREAD

**Issue by Marec4** [NFT-Limited/nf-bugs#218]
"Are you sure Archived this offer" - Archive this Offer?
"Confirm the Buy cancellation" - Cancel the buy Offer?
"Confirm the transfer cancellation" - Cancel the Transfer?
"Confirm the sell cancellation" - Cancel the Sell Offer?
"Confirm this Report on the NFT" - Report this NFT?
"Confirm this Report on the NFT" - Report this Collection?

![photo_2024-03-20_13-01-25 (2)](https://github.com/NFT-Limited/nf-bugs/assets/25827470/156b673d-2dbb-4430-b677-d0a3ed31b191)
![photo_2024-03-20_13-01-25](https://github.com/NFT-Limited/nf-bugs/assets/25827470/a7c750fe-c4bf-438f-9119-696039dbf287)
![photo_2024-03-20_13-01-24](https://github.com/NFT-Limited/nf-bugs/assets/25827470/9a0be69f-f861-40dc-b6fc-d70756fa1da8)
![photo_2024-03-20_13-01-23](https://github.com/NFT-Limited/nf-bugs/assets/25827470/46e89feb-8fbe-478a-a811-c3cc4b05e9b8)
![photo_2024-03-20_13-01-22](https://github.com/NFT-Limited/nf-bugs/assets/25827470/045b22ba-f183-47cc-a915-aecfbff36ae7)
![photo_2024-03-20_13-01-21](https://github.com/NFT-Limited/nf-bugs/assets/25827470/f41a5f38-fd7c-4353-aec8-50c19a4a5434)

**Comment by ajochems** [comment]
Some text are programatically created so the cancelations now are:
Cancel the buy?
Cancel the sell?
Cancel the transfer?

Report this Collection is going to be changed later as it reuses the same as Report this NFT and needs code changes to work
