### ISSUE TITLE
[BUG] Error reparsing colelctions

### ISSUE THREAD

**Issue by Marec4** [NFT-Limited/nf-bugs#220]
Reparsing collections gives an error. Few examples:

rBeistBLWtUskF2YzzSwMSM2tgsK7ZD7ME taxon 0
rUU4dn8yMXYRzD59AHqpkQXoPE6GfXaX5i taxon 423007336

**Comment by viktorhugo** [comment]
rUU4dn8yMXYRzD59AHqpkQXoPE6GfXaX5i taxon 423007336

 In this collection, your nfts do not have a valid URL to be processed. It's something like "https://bidds-test.onxrp.com/api/metadata/000813887AD00228AFC1C2CD67791597449BC2E6B9AD99CD08529E1805221BD5"

https://bithomp.com/nft/000813887AD00228AFC1C2CD67791597449BC2E6B9AD99CD08529E1805221BD5

**Comment by Marec4** [comment]
This is onxrp minted collection. They premint everything and then limit the access. Once minted on their site, the NFT will be made public.

You can see a lot of NFTs are visible on the collection while others are still hidden/limited: https://bithomp.com/nft-explorer?issuer=rUU4dn8yMXYRzD59AHqpkQXoPE6GfXaX5i

There another issue open regard that: https://github.com/orgs/NFT-Limited/projects/1/views/1?filterQuery=onxrp&pane=issue&itemId=31275126

rBeistBLWtUskF2YzzSwMSM2tgsK7ZD7ME taxon 0 also still giving the error.
