### ISSUE TITLE
[BUG] Random order with GridView banners

### ISSUE THREAD

**Issue by Marec4** [NFT-Limited/nf-bugs#221]
The random order with gridview banners is not working. Made all the banners random but they are still shown in the same order.

![Screenshot 2024-03-25 121842](https://github.com/NFT-Limited/nf-bugs/assets/25827470/1a02b98c-1d80-409f-a7bc-3fc266a3fb79)

**Comment by viktorhugo** [comment]
added to the system paremters GRIDVIEW_BANNERS_ORDER_XAPP to be able to change them
