### ISSUE TITLE
[Collection/NFT] Katana

### ISSUE THREAD

**Issue by danielwwf** [NFT-Limited/nf-bugs#25]
**Describe the issue**
Serial 1 to 4 (0 to 3) are not being displayed. Items not pinned, no image, no meta dat

**Details**
Help us to identify the collection by providing some infos:

REQUIRED
1. Issuer address: rBJmyqGCU4Mk2WF9p6xXB4VbmrkP7yjqpR
2. Collection Taxon: 0

**Additional context**
![image](https://user-images.githubusercontent.com/30388756/220092184-626ed885-8c9a-425d-afbf-f015e7381cb8.png)

**Comment by whywefight** [comment]
Four NFTs errored:

00082710710DE061A025E49168266A449ADAF5A51A60E15A0000099B00000000
00082710710DE061A025E49168266A449ADAF5A51A60E15A16E5DA9C00000001
00082710710DE061A025E49168266A449ADAF5A51A60E15A2DCBAB9D00000002
00082710710DE061A025E49168266A449ADAF5A51A60E15A44B17C9E00000003

**Comment by Marec4** [comment]
URI is faulty: 

![Image](https://user-images.githubusercontent.com/25827470/220851322-fefcb6d4-ddbb-47f5-81a6-5f4ddac7724c.png)

**Comment by viktorhugo** [comment]
this https://bithomp.com/nft/000813887AD00228AFC1C2CD67791597449BC2E6B9AD99CDEF68A01205221BDF  does not have a specific URI
