### ISSUE TITLE
[Collection/NFT] Astro

### ISSUE THREAD

**Issue by whywefight** [NFT-Limited/nf-bugs#26]
**Describe the issue**
No images being displayed. Items pinned but no meta data.

**Details**
Help us to identify the collection by providing some infos:

REQUIRED
1. Issuer address: rfMUi7pdXA6iDD5VMtHFHBMCSXF8abwXA6
2. Collection Taxon: 0

**Comment by whywefight** [comment]
partially synced

**Comment by Marec4** [comment]
Needs Reset/Parse
