### ISSUE TITLE
[Collection/NFT] XWizard

### ISSUE THREAD

**Issue by whywefight** [NFT-Limited/nf-bugs#27]
**Describe the issue**
No images are being displayed, no items pinned, no meta data.

**Details**
Help us to identify the collection by providing some infos:

REQUIRED
1. Issuer address: rWizQRjdHoBLuEjUoHdcFharvgsPKXd7q
2. Collection Taxon: 1958998591

**Comment by whywefight** [comment]
The whole collection errored.

Examples:
000A170205A5CACE52E5EB7C8E2A21AD7D3F4DCB7F6F0C054FD74D74000005B0
90BCF4D476AC2E29B3AE3FE3B409A81CD2A37F3321C3C23FBAA867FB677273D8

**Comment by Marec4** [comment]
Needs Reset/Parse

**Comment by danielwwf** [comment]
Triggered reset
