### ISSUE TITLE
[Collection/NFT] Wild Stag Treehouse

### ISSUE THREAD

**Issue by whywefight** [NFT-Limited/nf-bugs#29]
**Describe the issue**
No images are being displayed, no items pinned, no metadata.

**Details**
Help us to identify the collection by providing some infos:

REQUIRED
1. Issuer address: rLtgE7FjDfyJy5FGY87zoAuKtH6Bfb9QnE
2. Collection Taxon: 16

**Comment by whywefight** [comment]
The whole collection errored.

Example: 00081770DA305E2EC183969EA8D7FEB01AB4834F15616D0BE7134D1C00000271

**Comment by danielwwf** [comment]
There is apparently no URI

**Comment by danielwwf** [comment]
I just rechecked the collection, and the data now seems correct. However, if I trigger a reset on single items, we end up with a 400. The data is there. I checked oxps API manually, and minted items do return correctly. The collection is still in mint, and we should have at least 159 items.
