### ISSUE TITLE
[Collection/NFT] Aesthetes SRL Vip

### ISSUE THREAD

**Issue by danielwwf** [NFT-Limited/nf-bugs#31]
**Describe the issue**
No images are being displayed, no items pinned, no metadata.

**Details**
Help us to identify the collection by providing some infos:

REQUIRED
1. Issuer address: rHTPa44d171cVAtgdLGraGhvUB7QyHr4si
2. Collection Taxon: 0

**Comment by Marec4** [comment]
Error Message: checkedPinnedStatus Error: {}

When trying to reset getting this error message: Error Resetting and Parsing NFT
