### ISSUE TITLE
[Collection/NFT] Genesis Super Eagles

### ISSUE THREAD

**Issue by whywefight** [NFT-Limited/nf-bugs#32]
**Describe the issue**
No images are being displayed, no items pinned, no metadata.

**Details**
Help us to identify the collection by providing some infos:

REQUIRED
1. Issuer address: rGAME3VNR2gvbwwavVNHBcTCQyBiFmgjTt
2. Collection Taxon: 2086

**Comment by whywefight** [comment]
The whole collection errored.

Example: 00081388AED13F48BC82D3B7CB5C2E0530572769EC42070A188FA01800000415

**Comment by Marec4** [comment]
NFT Reset/Parse is working but this needs to be done with the whole collection
