### ISSUE TITLE
[Collection/NFT] Lézardrieux

### ISSUE THREAD

**Issue by danielwwf** [NFT-Limited/nf-bugs#33]
**Describe the issue**
No images are being displayed, no items pinned, no metadata.

**Details**
Help us to identify the collection by providing some infos:

REQUIRED
1. Issuer address: rpcMVexU5whBSGg7XZJDhBvSCNpj8wQx7j
2. Collection Taxon: 0

**Comment by whywefight** [comment]
partially synced

**Comment by Marec4** [comment]
Error message: checkedPinnedStatus Error: {}

When trying to Reset, getting this error: Error Resetting and Parsing NFT.
