### ISSUE TITLE
[Collection/NFT] BTS STUDIOS

### ISSUE THREAD

**Issue by whywefight** [NFT-Limited/nf-bugs#34]
**Describe the issue**
No images are being displayed, no items pinned, no metadata.

**Details**
Help us to identify the collection by providing some infos:

REQUIRED
1. Issuer address: r4KATfAJ8z8Nd7KrXc9RgFqe5iQjiuNRA6
2. Collection Taxon: 9

**Comment by Marec4** [comment]
mp4 videos

**Comment by Marec4** [comment]
Needs Reset/Parse
