### ISSUE TITLE
[Collection/NFT] Phoenix Eggs

### ISSUE THREAD

**Issue by whywefight** [NFT-Limited/nf-bugs#35]
**Describe the issue**
Some items are good on others no items pinned, no metadata.

**Details**
Help us to identify the collection by providing some infos:

REQUIRED
1. Issuer address: rUGwvh8XrxjApzEFUUPfFEAqManNuDaU5Y
2. Collection Taxon: 1

**Comment by danielwwf** [comment]
They are all in now. This is one of the collections not having an image, any chance we can get preview images for them? Like 1st frame. Thats how peerkat shows these files.

**Comment by Marec4** [comment]
We have issue #76 open for the preview image.
