### ISSUE TITLE
[Collection/NFT] XRock

### ISSUE THREAD

**Issue by whywefight** [NFT-Limited/nf-bugs#36]
**Describe the issue**
No images are being displayed, no items pinned, no metadata.

**Details**
Help us to identify the collection by providing some infos:

REQUIRED
1. Issuer address: rock3H4RNNVY4qPzweibGViM6CBqwiK3X
2. Collection Taxon: 241815311

**Comment by whywefight** [comment]
The whole collection errored.

Example: 000A170208D0F8B0F780849C9E10B8706203A819FE6B6D301A61D7170000017D

**Comment by Marec4** [comment]
Needs Reset/Parse
