### ISSUE TITLE
[BUG] Portfolio search for accounts not working

### ISSUE THREAD

**Issue by whywefight** [NFT-Limited/nf-bugs#4]
**Describe the bug**
It is currently only possible to search per nfttokenid. Searching for an account results in an empty "All my NFTs" area.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open NF
2. Go to Portfolio
3. Paste account you want to look at in
4. "All my NFTs" is now blank. 

**Expected behaviour**
When searching for an account, all NFTs owned by the account should be shown in "All My NFTs" and the label of the section should change to the account one is searching for.

**Screenshots**
![image](https://user-images.githubusercontent.com/30388756/219857421-fd0977ed-22bb-47e4-ad01-ce59dd38048e.png)

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All
 - Non Fungible Version 0.3.9
 - Non Fungible Theme all
 - XUMM Version 2.3.9
 - XUMM Theme light

**Additional context**
This worked before.

**Comment by danielwwf** [comment]
Fixed.
