### ISSUE TITLE
[Collection/NFT] XFantasy

### ISSUE THREAD

**Issue by Marec4** [NFT-Limited/nf-bugs#41]
**Describe the issue**
No images are being displayed, items are pinned, no metadata.

**Details**
Help us to identify the collection by providing some infos:

REQUIRED
1. Issuer address: rasztbhPYot9JM8YgWcePe8UXh2fpWURCC
2. Collection Taxon: 1

**Comment by Marec4** [comment]
Needs Reset/Parse

**Comment by danielwwf** [comment]
Triggered reset
