### ISSUE TITLE
[Collection/NFT] WWF-Animal Buddies

### ISSUE THREAD

**Issue by Marec4** [NFT-Limited/nf-bugs#42]
**Describe the issue**
No images are being displayed, items are pinned, metadata is ok.

**Details**
Help us to identify the collection by providing some infos:

REQUIRED
1. Issuer address: rpPKhrxAvi4HHFmtd8XdxRf8nAsj92ivyT
2. Collection Taxon: 0

**Comment by Marec4** [comment]
Needs Reset/Parse

**Comment by danielwwf** [comment]
Triggered reset, problem was we identified all as PDF
