### ISSUE TITLE
[Collection/NFT] ApeX

### ISSUE THREAD

**Issue by Marec4** [NFT-Limited/nf-bugs#43]
**Describe the issue**
No images are being displayed, items are pinned, no metadata.

**Details**
Help us to identify the collection by providing some infos:

REQUIRED
1. Issuer address: rHF2GbxEj6Aen6cGJZGijRiyxEiHAJrYyp
2. Collection Taxon: 0

**Comment by whywefight** [comment]
As of now, partially synced
