### ISSUE TITLE
[Collection/NFT] Maasai

### ISSUE THREAD

**Issue by Marec4** [NFT-Limited/nf-bugs#44]
**Describe the issue**
No images are being displayed, items are pinned, no metadata.

**Details**
Help us to identify the collection by providing some infos:

REQUIRED
1. Issuer address: rKwKgshquGeVFuHFgCoqvDcGsTnAoM7CL1
2. Collection Taxon: 0

**Comment by whywefight** [comment]
As of now, partially synced
