### ISSUE TITLE
[Collection/NFT] xElon

### ISSUE THREAD

**Issue by Marec4** [NFT-Limited/nf-bugs#46]
**Describe the issue**
No images are being displayed, no items pinned, no metadata.

**Details**
Help us to identify the collection by providing some infos:

REQUIRED
1. Issuer address: rfkwiAyQx884xGGWUNDDhp5DjMTtwdrQVd
2. Collection Taxon: 39

**Comment by Marec4** [comment]
Partially parsed

**Comment by Marec4** [comment]
2 NFTs have errors and not loading even after the reset. (error 400)
00081B5849FADF6C7A01A0E688CE287D26614632CB7F2F683F8E01C500000147
00081B5849FADF6C7A01A0E688CE287D26614632CB7F2F685673D2C400000148

**Comment by viktorhugo** [comment]
00081B5849FADF6C7A01A0E688CE287D26614632CB7F2F683F8E01C500000147
this nft has not been sold (nft No URI specified)
