### ISSUE TITLE
[Collection/NFT] XGangster Apes

### ISSUE THREAD

**Issue by Marec4** [NFT-Limited/nf-bugs#47]
**Describe the issue**
No images are being displayed, items are pinned, no metadata.

**Details**
Help us to identify the collection by providing some infos:

REQUIRED
1. Issuer address: rp2BHRnqRpLVAzD6rRETYbUGLvDPZE4rAN
2. Collection Taxon: 5268

**Comment by whywefight** [comment]
It seems to snyc. As of writing this 70+ images were missing.
