### ISSUE TITLE
[Collection/NFT] SHROOM BLASTER

### ISSUE THREAD

**Issue by Marec4** [NFT-Limited/nf-bugs#48]
**Describe the issue**
No images are being displayed, no items pinned, no metadata.

**Details**
Help us to identify the collection by providing some infos:

REQUIRED
1. Issuer address: rpp8qnQ4f73Us1yEBs13FJvmsuZAMZAvGc
2. Collection Taxon: 30201360

**Comment by whywefight** [comment]
partially synced

**Comment by whywefight** [comment]
None of the NFTs has a valid URI. Based on garbage in and garbage out, this issue is closed.
