### ISSUE TITLE
[Collection/NFT] Chiefape

### ISSUE THREAD

**Issue by Marec4** [NFT-Limited/nf-bugs#49]
**Describe the issue**
No images are being displayed, items are pinned, no metadata.

**Details**
Help us to identify the collection by providing some infos:

REQUIRED
1. Issuer address: rwRXwALbrnD5D7pNrdEtScQVRDKXTTLPjF
2. Collection Taxon: 115

**Comment by whywefight** [comment]
partially synced

**Comment by Marec4** [comment]
Needs Reset/Parse
