### ISSUE TITLE
[FEATURE REQUEST] NFT Swap

### ISSUE THREAD

**Issue by whywefight** [NFT-Limited/nf-bugs#5]
**Is your feature request related to a problem? Please describe.**
It would be great if users could swap/transfer (sending NFTs for 0XRP/Tokens). Currently, that's only possible via MPs.

**Describe the solution you'd like**
Whenever the user is viewing an NFT in possession, they should have an option to send it. It should ask for the receiver's account (Addressbook access possible?) and then sign the tx.

The receiver should get a notification about the transfer and be able to sign it. We should look into where to place it in regard to future features like buying/selling/offer management. 

**Describe alternatives you've considered**
There are none.

**Additional context**
None

**Comment by danielwwf** [comment]
I think there is no point in doing the transfer inside NF other than showing pending ones on the future MP tab, as this is now directly handled via XUMM https://twitter.com/WietseWind/status/1629277446737469441

We would have to fall back on signing, just calling the pending one a trigger the sign should be good.

**Comment by danielwwf** [comment]
Reviewed this again. We still need to initiate the transfer (send out)

**Comment by Marec4** [comment]
XUMM will handle this: https://twitter.com/WietseWind/status/1629277446737469441?s=20
