### ISSUE TITLE
[Collection/NFT] XRPlaymates

### ISSUE THREAD

**Issue by Marec4** [NFT-Limited/nf-bugs#50]
**Describe the issue**
Some images are not being displayed, no items pinned, images that are not displayed are missing metadata.

Few examples of NFTs that are not being displayed:
00081388366BB61FD164F8D748C9A964D95299D9A53F3F526E981041000000CE
00081388366BB61FD164F8D748C9A964D95299D9A53F3F5298CFF243000000D0
00080000366BB61FD164F8D748C9A964D95299D9A53F3F52CAF35445000000D2

**Details**
Help us to identify the collection by providing some infos:

REQUIRED
1. Issuer address: rnxkXHDxjJknJnxxMaAYmmJ1Sr1z2oAoQq
2. Collection Taxon: 41297960

**Comment by whywefight** [comment]
partially synced

**Comment by Marec4** [comment]
Only 2 NFTs missing:
00081388366BB61FD164F8D748C9A964D95299D9A53F3F5298CFF243000000D0
00081388366BB61FD164F8D748C9A964D95299D9A53F3F52AF098E5F000000DC

**Comment by Marec4** [comment]
Still an issue with the 2 NFTs mentioned in last comment
