### ISSUE TITLE
[Collection/NFT] xDREAMS 2nd Gen

### ISSUE THREAD

**Issue by Marec4** [NFT-Limited/nf-bugs#51]
**Describe the issue**
An image is not being displayed, no items pinned, the image that is not displayed is missing metadata.

Missing image:
00081B5890813F8A0160A44F65F45169E616660FFC89FC250B9B7A96000003C2

**Details**
Help us to identify the collection by providing some infos:

REQUIRED
1. Issuer address: rNBn3A1nR1qGBfLX2GpuYjLz2Rq58jjCTS
2. Collection Taxon: 5579

**Comment by whywefight** [comment]
Most images working as of the time of writing this. 00081B5890813F8A0160A44F65F45169E616660FFC89FC250B9B7A96000003C2 errored.

**Comment by Marec4** [comment]
Did Reset/Parse and it's working now.
