### ISSUE TITLE
[Collection/NFT] Bored Seagull Club

### ISSUE THREAD

**Issue by Marec4** [NFT-Limited/nf-bugs#52]
**Describe the issue**
No images are being displayed, items are pinned, metadata is ok.

**Details**
Help us to identify the collection by providing some infos:

REQUIRED
1. Issuer address: rftc7W745AzRikYjWDn669nCE4CNNttzcz
2. Collection Taxon: 23173

**Comment by Marec4** [comment]
Collection needs Reset/Parse

**Comment by Marec4** [comment]
Some NFTs still missing, but they are appearing with manual reset.

**Comment by danielwwf** [comment]
Did a manual reset on the missing ones.
