### ISSUE TITLE
[Collection/NFT] Faucet SuperEagles

### ISSUE THREAD

**Issue by Marec4** [NFT-Limited/nf-bugs#54]
**Describe the issue**
No images are being displayed, no items pinned, metadata is ok.

**Details**
Help us to identify the collection by providing some infos:

REQUIRED
1. Issuer address: rGAME3VNR2gvbwwavVNHBcTCQyBiFmgjTt
2. Collection Taxon: 1637774760

**Comment by whywefight** [comment]
The whole collection errored.
