### ISSUE TITLE
[Collection] ArtyFartyAnimal Airdrop Ratties

### ISSUE THREAD

**Issue by whywefight** [NFT-Limited/nf-bugs#6]
**Describe the issue**
We can not display AFAs in app and have missing data on the backend.

**Details**
Help us to identify the collection by providing some infos:

REQUIRED
1. Issuer address: ratAFANfrYBBcJetey1ogtafrUfwjWsxi6
2. Collection Taxon: 1

OPTIONAL - Provide missing information or let us know if we should update something.
Examples:
https://bithomp.com/nft/00083A9840AB9C1BB46EC7B01043DE144D87E9FBEC4D4151E9590545000002A9
https://bithomp.com/nft/00083A9840AB9C1BB46EC7B01043DE144D87E9FBEC4D41511724A747000002AB
https://bithomp.com/nft/00083A9840AB9C1BB46EC7B01043DE144D87E9FBEC4D4151003ED644000002AA
https://bithomp.com/nft/00083A9840AB9C1BB46EC7B01043DE144D87E9FBEC4D41512E0A7846000002AC

**Additional context**
Backend DOES NOT show metadata and not a single NFT has been pinned and we couldn't identify the media type.

**Comment by danielwwf** [comment]
We are now displaying all but not one item is pinned. Also no Raw Data avilable.

**Comment by Marec4** [comment]
Need to Reset/Parse the whole collection. Did manually a few and it's showing pinned after that.

Some images show pinned but not showing up after the reset.

**Comment by danielwwf** [comment]
Not being pinned yet but all should be displayed

**Comment by danielwwf** [comment]
00083A9840AB9C1BB46EC7B01043DE144D87E9FBEC4D41515B974D9E00000004

**Comment by danielwwf** [comment]
Still not a single image pinned @ajochems
