### ISSUE TITLE
[Collection/NFT] BLADE X SHOP

### ISSUE THREAD

**Issue by Marec4** [NFT-Limited/nf-bugs#60]
**Describe the issue**
Some images are being displayed some not, items are pinned, no metadata on those missing image.

**Details**
Help us to identify the collection by providing some infos:

REQUIRED
1. Issuer address: rKSKUtDNTamLFa9aaMdN28VZuSCTzt3oMj
2. Collection Taxon: 11256

**Comment by whywefight** [comment]
partially synced

**Comment by Marec4** [comment]
Missing first 13 images.
