### ISSUE TITLE
[Collection/NFT] X-Nunk/s XNE

### ISSUE THREAD

**Issue by Marec4** [NFT-Limited/nf-bugs#67]
**Describe the issue**
No images are being displayed, no items pinned, no metadata.

**Details**
Help us to identify the collection by providing some infos:

REQUIRED
1. Issuer address: rHDnWxxKzZTZ9C7H39n1G5ohAaPDxVqd5N
2. Collection Taxon: 223

**Comment by Marec4** [comment]
Using "animation" attribute for gif instead of "image"

![Image](https://user-images.githubusercontent.com/25827470/220560781-1b412cb1-b407-4955-ab4a-07cce0caeca0.png)

**Comment by danielwwf** [comment]
reset all collection for issuer rHDnWxxKzZTZ9C7H39n1G5ohAaPDxVqd5N

**Comment by danielwwf** [comment]
Fixed
