### ISSUE TITLE
[Collection/NFT] X-Nunk/s

### ISSUE THREAD

**Issue by Marec4** [NFT-Limited/nf-bugs#71]
**Describe the issue**
No images are being displayed, no items pinned, no metadata.

**Details**
Help us to identify the collection by providing some infos:

REQUIRED
1. Issuer address: rHDnWxxKzZTZ9C7H39n1G5ohAaPDxVqd5N
2. Collection Taxon: 75

**Comment by danielwwf** [comment]
Prob best to reset all NFTs by that issuer
