### ISSUE TITLE
[Collection/NFT] Project MoonFace Presents-Morph

### ISSUE THREAD

**Issue by Marec4** [NFT-Limited/nf-bugs#72]
**Describe the issue**
No images are being displayed, no items pinned, no metadata.

**Details**
Help us to identify the collection by providing some infos:

REQUIRED
1. Issuer address: rHfidvQp1i5Vyk9GE6DRoP53Q5iPt8eot3
2. Collection Taxon: 533

**Comment by whywefight** [comment]
Errored on rescan with {}. Not metadata.

**Comment by Marec4** [comment]
mp4 files

**Comment by danielwwf** [comment]
Content type not detected correct
