### ISSUE TITLE
[Collection/NFT] Revellers

### ISSUE THREAD

**Issue by whywefight** [NFT-Limited/nf-bugs#77]
**Describe the issue**
Still needs to be fully synced. Some NFTs on error 404. No URI is specified in the metadata (https://bithomp.com/nfts/rRVLLRSgfcuuDBA4GT7gfAmTXvovsvZCH).

**Details**
This should be in the batch we are currently working on.

REQUIRED
1. Issuer address: rRVLLRSgfcuuDBA4GT7gfAmTXvovsvZCH
2. Collection Taxon: 40639

**Comment by danielwwf** [comment]
Collection is in mint via oxp, This goes back into having a filter for the 404's returned by their api

**Comment by Marec4** [comment]
We have issue #82 open for the onXRP issue. Other than that the collection is ok.
