### ISSUE TITLE
[Collection/NFT] XRP Clan

### ISSUE THREAD

**Issue by danielwwf** [NFT-Limited/nf-bugs#83]
**Describe the issue**
There was one item missing 000803E8D35BEF2357E90BA8CED030D8F7B59C19A6D1582E1D4BE7110000002E. Refreshing didn't bring it back. Refreshed another one we had after doing so it went missing as well 000803E8D35BEF2357E90BA8CED030D8F7B59C19A6D1582E1D4BE7110000002E

**Details**
Help us to identify the collection by providing some infos:

REQUIRED
1. Issuer address: rLGZ5wxF6z6iym8tFimmt1mp1RNVkbJv3A
2. Collection Taxon: 28888

**Comment by Marec4** [comment]
Error message: {}
