### ISSUE TITLE
[FEATURE REQUEST] Change the way NFTs with multiple media files is displayed

### ISSUE THREAD

**Issue by danielwwf** [NFT-Limited/nf-bugs#9]
**Is your feature request related to a problem? Please describe.**
Some NFTs do have more than one media type. E.g. image + audio or image + video. In this case, we should display them like bithomp does. 

**Describe the solution you'd like**
Bithomp allows you to toggle what you look at. For the example given, you can either look at the image or the video file. We should copy the way they are handling it.

**Describe alternatives you've considered**
The current way is the alternative where the grid preview shows the image, and the detailed view shows the media view. This isn't ideal.

**Additional context**
Example NFT: https://bithomp.com/nft/00080FA06F8B963680E287FFF0B75D11E2A81D529209B944EA93049700000FFB
Screenshot: 
![image](https://user-images.githubusercontent.com/30388756/219945865-5012033b-4239-4bce-ab79-403da02a6924.png)

**Comment by Marec4** [comment]
Grid view is ok but when I open NFT detail view, there's no way to switch between image and video:




![Image](https://github.com/NFT-Limited/nf-bugs/assets/25827470/33cc09f2-5e3d-4bae-b19e-0b88a6edeee9)



![Image](https://github.com/NFT-Limited/nf-bugs/assets/25827470/09dd57c4-d9d5-48dd-806e-6d03ac34a1c3)

**Comment by Marec4** [comment]
Yes, it is good now with the image/video switching. 

Change the font, so that it's visible when it's active.



![Image](https://github.com/NFT-Limited/nf-bugs/assets/25827470/32b9e7c5-157e-494d-aff3-31f8a4a89832)
