### ISSUE TITLE
[Collection/NFT] Xbeards Boxing Bonus

### ISSUE THREAD

**Issue by Marec4** [NFT-Limited/nf-bugs#94]
**Describe the issue**
Not showing 5 NFTs from the collection. Reset didn't help.
00081388A0AC3ED1865D08CD9B203C93C84E8C6F8E98E059732754A20000032A
00081388A0AC3ED1865D08CD9B203C93C84E8C6F8E98E0598A0D25A10000032B
00081388A0AC3ED1865D08CD9B203C93C84E8C6F8E98E059A0F2FAA00000032C
00081388A0AC3ED1865D08CD9B203C93C84E8C6F8E98E05913700FAB00000331
00081388A0AC3ED1865D08CD9B203C93C84E8C6F8E98E05902EFFB9F0000035D

**Details**
Help us to identify the collection by providing some infos:

REQUIRED
1. Issuer address: rEeZTW64fTwErNvKfh29ZtEBVvy2dtN3kV
2. Collection Taxon: 615

**Comment by Marec4** [comment]
This is the error message: checkedPinnedStatus Error: {}

**Comment by viktorhugo** [comment]
00081388A0AC3ED1865D08CD9B203C93C84E8C6F8E98E059732754A20000032A
00081388A0AC3ED1865D08CD9B203C93C84E8C6F8E98E0598A0D25A10000032B
00081388A0AC3ED1865D08CD9B203C93C84E8C6F8E98E059A0F2FAA00000032C
00081388A0AC3ED1865D08CD9B203C93C84E8C6F8E98E05913700FAB00000331

no media was found in these nfts
